<?php

namespace ccxt\async;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\async\abstract\cube as Exchange;

class cube extends Exchange {

    public function describe() {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'cube',
            'name' => 'Cube Exchange',
            'countries' => array( 'AU', 'PL' ), // TODO
            'version' => 'v1',
            // 'rateLimit' => 100,
            'pro' => false, // TODO
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'cancelAllOrders' => false, // TODO
                'cancelOrder' => true, // TODO
                'cancelOrders' => false,
                'createOrder' => true, // TODO
                'editOrder' => false,
                'fetchBalance' => true, // TODO
                'fetchBorrowRate' => false,
                'fetchBorrowRateHistories' => false,
                'fetchBorrowRateHistory' => false,
                'fetchBorrowRates' => false,
                'fetchClosedOrders' => false,
                'fetchCurrencies' => false,
                'fetchDepositAddress' => false,
                'fetchDeposits' => false,
                'fetchFundingHistory' => false,
                'fetchFundingRate' => false,
                'fetchFundingRateHistory' => false,
                'fetchFundingRates' => false,
                'fetchIndexOHLCV' => false,
                'fetchMarginMode' => false,
                'fetchMarkets' => true, // TODO
                'fetchMarkOHLCV' => false,
                'fetchMyTrades' => true, // TODO
                'fetchOHLCV' => true, // TODO
                'fetchOpenInterestHistory' => false,
                'fetchOpenOrders' => true, // TODO
                'fetchOrder' => true, // TODO
                'fetchOrderBook' => true, // todo
                'fetchOrders' => false,
                'fetchOrderTrades' => true, // TODO
                'fetchPositionMode' => false,
                'fetchPositions' => false,
                'fetchPremiumIndexOHLCV' => false,
                'fetchTicker' => true, // TODO
                'fetchTickers' => true, // TODO
                'fetchTime' => false,
                'fetchTrades' => false,
                'fetchTradingFee' => false,
                'fetchTradingFees' => false,
                'fetchTransactionFees' => false,
                'fetchTransactions' => false,
                'fetchTransfer' => false,
                'fetchTransfers' => false,
                'fetchWithdrawal' => false,
                'fetchWithdrawals' => false,
                'setLeverage' => false,
                'setMarginMode' => false,
                'transfer' => false,
                'withdraw' => false,
                'ws' => false,
            ),
            'timeframes' => array(
                '1m' => 1,
                '5m' => 5,
                '10m' => 10,
                '30m' => 10,
                '1h' => 60,
                '2h' => 120,
                '4h' => 240,
                '8h' => 480,
                '12h' => 720,
                '1d' => 24,
                '1w' => 70,
                '1M' => 31,
            ),
            'urls' => array(
                'logo' => 'https://avatars.githubusercontent.com/u/128435657?s=200&v=4',
                'api' => array(
                    'http' => 'https://cube.exchange',
                    'ws' => 'ws://cube.exchange',
                ),
                'www' => 'https://cube.exchange/',
                'doc' => array(
                    'https://cube.exchange/docs',
                ),
                'fees' => 'https://helpcenter.ace.io/hc/zh-tw/articles/360018609132-%E8%B2%BB%E7%8E%87%E8%AA%AA%E6%98%8E',
            ),
            'requiredCredentials' => array(
                'apiKey' => true,
                'secret' => true,
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        '/ir/v0/markets',
                    ),
                ),
                'private' => array(
                    'post' => array(
                    ),
                ),
            ),
            'fees' => array(
                'trading' => array(
                    'percentage' => true,
                    'maker' => $this->parse_number('0.0'),
                    'taker' => $this->parse_number('0.0'),
                ),
            ),
            'options' => array(
                'brokerId' => 'ccxt',
            ),
            'commonCurrencies' => array(
            ),
        ));
    }
}
