# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.cube import ImplicitAPI


class cube(Exchange, ImplicitAPI):

    def describe(self):
        return self.deep_extend(super(cube, self).describe(), {
            'id': 'cube',
            'name': 'Cube Exchange',
            'countries': ['AU', 'PL'],  # TODO
            'version': 'v1',
            # 'rateLimit': 100,
            'pro': False,  # TODO
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'cancelAllOrders': False,  # TODO
                'cancelOrder': True,  # TODO
                'cancelOrders': False,
                'createOrder': True,  # TODO
                'editOrder': False,
                'fetchBalance': True,  # TODO
                'fetchBorrowRate': False,
                'fetchBorrowRateHistories': False,
                'fetchBorrowRateHistory': False,
                'fetchBorrowRates': False,
                'fetchClosedOrders': False,
                'fetchCurrencies': False,
                'fetchDepositAddress': False,
                'fetchDeposits': False,
                'fetchFundingHistory': False,
                'fetchFundingRate': False,
                'fetchFundingRateHistory': False,
                'fetchFundingRates': False,
                'fetchIndexOHLCV': False,
                'fetchMarginMode': False,
                'fetchMarkets': True,  # TODO
                'fetchMarkOHLCV': False,
                'fetchMyTrades': True,  # TODO
                'fetchOHLCV': True,  # TODO
                'fetchOpenInterestHistory': False,
                'fetchOpenOrders': True,  # TODO
                'fetchOrder': True,  # TODO
                'fetchOrderBook': True,  # todo
                'fetchOrders': False,
                'fetchOrderTrades': True,  # TODO
                'fetchPositionMode': False,
                'fetchPositions': False,
                'fetchPremiumIndexOHLCV': False,
                'fetchTicker': True,  # TODO
                'fetchTickers': True,  # TODO
                'fetchTime': False,
                'fetchTrades': False,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
                'fetchTransactionFees': False,
                'fetchTransactions': False,
                'fetchTransfer': False,
                'fetchTransfers': False,
                'fetchWithdrawal': False,
                'fetchWithdrawals': False,
                'setLeverage': False,
                'setMarginMode': False,
                'transfer': False,
                'withdraw': False,
                'ws': False,
            },
            'timeframes': {
                '1m': 1,
                '5m': 5,
                '10m': 10,
                '30m': 10,
                '1h': 60,
                '2h': 120,
                '4h': 240,
                '8h': 480,
                '12h': 720,
                '1d': 24,
                '1w': 70,
                '1M': 31,
            },
            'urls': {
                'logo': 'https://avatars.githubusercontent.com/u/128435657?s=200&v=4',
                'api': {
                    'http': 'https://cube.exchange',
                    'ws': 'ws://cube.exchange',
                },
                'www': 'https://cube.exchange/',
                'doc': [
                    'https://cube.exchange/docs',
                ],
                'fees': 'https://helpcenter.ace.io/hc/zh-tw/articles/360018609132-%E8%B2%BB%E7%8E%87%E8%AA%AA%E6%98%8E',
            },
            'requiredCredentials': {
                'apiKey': True,
                'secret': True,
            },
            'api': {
                'public': {
                    'get': [
                        '/ir/v0/markets',
                    ],
                },
                'private': {
                    'post': [
                    ],
                },
            },
            'fees': {
                'trading': {
                    'percentage': True,
                    'maker': self.parse_number('0.0'),
                    'taker': self.parse_number('0.0'),
                },
            },
            'options': {
                'brokerId': 'ccxt',
            },
            'commonCurrencies': {
            },
        })
